- name: Create app dir
  become: yes
  file:
    path: /home/ubuntu/app
    state: directory

- name: Copy backend files
  become: yes
  unarchive:
    src: /tmp/workspace/backend.tar.gz
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "Copy package.json files"
  become: yes
  copy:
    src: /tmp/workspace/package.json
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "NPM Install"
  shell:
    cmd: npm install --production
    chdir: /home/ubuntu/app

- name: Start PM2
  become: yes
  shell: |
    cd /home/ubuntu/app
    pm2 start main.js --name app