---
- name: "Update apt packages"
  become: yes
  apt:
    update_cache: "yes"

- name: "Upgrade apt packages"
  become: yes
  apt:
    upgrade: "yes"

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    update_cache: "yes"

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/app
    state: directory

- name: Transfer backend files to cloud server
  copy:
    src: /root/project/backend/
    dest: ~/app/
    owner: ubuntu

- name: "NPM Install"
  shell:
    cmd: npm install --production
    chdir: ~/app


- name: "Executing node"
  shell: | 
    pm2 start ~/app/main.js -f
  
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env','TYPEORM_MIGRATIONS_DIR') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}" 